import type { Locale, Tour } from "@/types/travel";

const images: Record<string, string> = {
  antalya: "/destinations/antalya.jpg",
  dubai: "/destinations/dubai.jpg",
  sharm: "/destinations/sharm.jpg",
  phuket: "/destinations/phuket.jpg",
  bali: "/destinations/bali.jpg",
  sochi: "/destinations/sochi.jpg"
};

const countryLabels: Record<string, Record<Locale, string>> = {
  Egypt: { ru: "Египет", en: "Egypt" },
  Indonesia: { ru: "Индонезия", en: "Indonesia" },
  Russia: { ru: "Россия", en: "Russia" },
  Thailand: { ru: "Таиланд", en: "Thailand" },
  Turkey: { ru: "Турция", en: "Turkey" },
  UAE: { ru: "ОАЭ", en: "UAE" }
};

const cityLabels: Record<string, Record<Locale, string>> = {
  Antalya: { ru: "Анталья", en: "Antalya" },
  Bali: { ru: "Бали", en: "Bali" },
  Dubai: { ru: "Дубай", en: "Dubai" },
  Phuket: { ru: "Пхукет", en: "Phuket" },
  "Sharm El Sheikh": { ru: "Шарм-эль-Шейх", en: "Sharm El Sheikh" },
  Sochi: { ru: "Сочи", en: "Sochi" }
};

const includedLabels: Record<string, Record<Locale, string>> = {
  "All inclusive": { ru: "Все включено", en: "All inclusive" },
  Breakfast: { ru: "Завтраки", en: "Breakfast" },
  Flight: { ru: "Перелет", en: "Flight" },
  "Half board": { ru: "Полупансион", en: "Half board" },
  Hotel: { ru: "Отель", en: "Hotel" },
  Transfer: { ru: "Трансфер", en: "Transfer" }
};

const ruTourDescriptions: Record<string, string> = {
  "antalya-lara-family": "Спокойный пляжный отдых по системе все включено: мелкая вода, бассейны и короткий трансфер.",
  "antalya-belek-golf": "Зеленая курортная зона для комфортных пляжных дней и неспешных вечерних прогулок.",
  "antalya-old-town": "Компактная поездка с пляжными утрами, вечерами в старом городе и прогулками вдоль побережья.",
  "antalya-kemer": "Пляжный курорт среди сосновых склонов, морских прогулок и более прохладных вечеров.",
  "dubai-jumeirah": "Городской пляжный отдых с моллами, ресторанами и удобной инфраструктурой отеля.",
  "dubai-marina": "Поездка с фокусом на город: вечера у воды и дневные планы в кондиционированном комфорте.",
  "dubai-family-palm": "Семейный курорт с бассейнами, детским клубом и удобным выходом к пляжу.",
  "dubai-stopover": "Короткий городской перерыв с видами на небоскребы и вечерними экскурсиями.",
  "sharm-naama": "Классический отдых на Красном море: теплая вода, пляжный ритм и вечерний променад.",
  "sharm-reef": "Пляжная неделя для снорклинга с домашним рифом и тихими вечерами.",
  "sharm-family": "Семейный курорт с водными горками, детским клубом и простым доступом к пляжу.",
  "sharm-sinai": "Пляжная база для морских прогулок и коротких экскурсий в пустыню.",
  "phuket-karon": "Тропическая пляжная поездка рядом с кафе и длинной песчаной береговой линией.",
  "phuket-kata-family": "Семейный отель с бассейном, спокойным районом и гибким планом питания.",
  "phuket-island-hop": "Бюджетная база для поездок по островам, рынков и активных вечеров.",
  "phuket-quiet": "Более тихий уголок Пхукета для медленных утр, прогулок по пляжу и локальных кафе.",
  "bali-nusa-dua": "Аккуратный пляжный курорт со спокойным ритмом и надежной отельной инфраструктурой.",
  "bali-ubud": "Зеленое размещение в глубине острова для прогулок, кафе, храмов и поездок на день.",
  "bali-canggu": "Пляжные кафе, закаты и расслабленный островной ритм.",
  "bali-family": "Более мягкая пляжная зона со спокойным темпом и семейными отелями.",
  "sochi-imereti": "Отдых на Черном море с набережной, пляжами и удобным трансфером из аэропорта.",
  "sochi-family": "Семейная поездка с бассейном, доступом к пляжу и короткими переездами.",
  "sochi-rosa": "Горный воздух, прогулки, канатные дороги и прохладные вечера недалеко от моря.",
  "sochi-short": "Короткий городской уикенд у моря: прогулки, кафе и быстрые выходы на пляж."
};

export function getTourCopy(tour: Tour, locale: Locale) {
  return {
    city: cityLabels[tour.city]?.[locale] ?? tour.city,
    country: countryLabels[tour.country]?.[locale] ?? tour.country,
    description: locale === "ru" ? (ruTourDescriptions[tour.id] ?? tour.description) : tour.description,
    hotelName: tour.hotelName,
    included: tour.included.map((item) => includedLabels[item]?.[locale] ?? item),
    title: tour.title
  };
}

export const mockTours: Tour[] = [
  {
    id: "antalya-lara-family",
    title: "Lara Family Sun",
    destinationId: "antalya",
    country: "Turkey",
    city: "Antalya",
    hotelName: "Lara Garden Resort 5*",
    description: "A relaxed all-inclusive beach stay with shallow water, pools and short transfer.",
    price: 189000,
    currency: "RUB",
    startDate: "2026-06-20",
    endDate: "2026-06-27",
    duration: 7,
    image: images.antalya,
    tags: ["beach", "family"],
    included: ["Flight", "Hotel", "All inclusive", "Transfer"],
    leadContactTarget: "Antalya desk"
  },
  {
    id: "antalya-belek-golf",
    title: "Belek Calm Coast",
    destinationId: "antalya",
    country: "Turkey",
    city: "Antalya",
    hotelName: "Belek Pine Club 5*",
    description: "Green resort area for comfortable beach days and unhurried evening walks.",
    price: 214000,
    currency: "RUB",
    startDate: "2026-06-22",
    endDate: "2026-06-30",
    duration: 8,
    image: images.antalya,
    tags: ["beach", "walk"],
    included: ["Flight", "Hotel", "Breakfast", "Transfer"],
    leadContactTarget: "Antalya desk"
  },
  {
    id: "antalya-old-town",
    title: "Kaleici Walk & Sea",
    destinationId: "antalya",
    country: "Turkey",
    city: "Antalya",
    hotelName: "Old Town Harbor Hotel 4*",
    description: "A compact trip for beach mornings, old town evenings and scenic coastal walks.",
    price: 151000,
    currency: "RUB",
    startDate: "2026-06-21",
    endDate: "2026-06-26",
    duration: 5,
    image: images.antalya,
    tags: ["walk", "excursion"],
    included: ["Flight", "Hotel", "Breakfast"],
    leadContactTarget: "Antalya desk"
  },
  {
    id: "antalya-kemer",
    title: "Kemer Mountain Bay",
    destinationId: "antalya",
    country: "Turkey",
    city: "Antalya",
    hotelName: "Kemer Blue Bay 4*",
    description: "Beach resort with pine-covered hills, boat trips and cooler evening air.",
    price: 176000,
    currency: "RUB",
    startDate: "2026-06-25",
    endDate: "2026-07-02",
    duration: 7,
    image: images.antalya,
    tags: ["beach", "excursion"],
    included: ["Flight", "Hotel", "Half board", "Transfer"],
    leadContactTarget: "Antalya desk"
  },
  {
    id: "dubai-jumeirah",
    title: "Jumeirah City Beach",
    destinationId: "dubai",
    country: "UAE",
    city: "Dubai",
    hotelName: "Jumeirah Shore 5*",
    description: "Urban beach holiday with malls, restaurants and comfortable hotel infrastructure.",
    price: 268000,
    currency: "RUB",
    startDate: "2026-06-20",
    endDate: "2026-06-27",
    duration: 7,
    image: images.dubai,
    tags: ["beach", "family"],
    included: ["Flight", "Hotel", "Breakfast", "Transfer"],
    leadContactTarget: "Dubai desk"
  },
  {
    id: "dubai-marina",
    title: "Marina Evening Lights",
    destinationId: "dubai",
    country: "UAE",
    city: "Dubai",
    hotelName: "Marina View Suites 4*",
    description: "City-first trip for evenings by the water and day plans with air-conditioned comfort.",
    price: 221000,
    currency: "RUB",
    startDate: "2026-06-23",
    endDate: "2026-06-29",
    duration: 6,
    image: images.dubai,
    tags: ["walk", "excursion"],
    included: ["Flight", "Hotel", "Breakfast"],
    leadContactTarget: "Dubai desk"
  },
  {
    id: "dubai-family-palm",
    title: "Palm Family Escape",
    destinationId: "dubai",
    country: "UAE",
    city: "Dubai",
    hotelName: "Palm Lagoon Resort 5*",
    description: "Family resort with pools, kids club and easy beach access.",
    price: 319000,
    currency: "RUB",
    startDate: "2026-06-26",
    endDate: "2026-07-03",
    duration: 7,
    image: images.dubai,
    tags: ["family", "beach"],
    included: ["Flight", "Hotel", "Half board", "Transfer"],
    leadContactTarget: "Dubai desk"
  },
  {
    id: "dubai-stopover",
    title: "Dubai Short Stop",
    destinationId: "dubai",
    country: "UAE",
    city: "Dubai",
    hotelName: "Downtown Compact 4*",
    description: "Short city break with skyline views and evening excursions.",
    price: 139000,
    currency: "RUB",
    startDate: "2026-06-21",
    endDate: "2026-06-25",
    duration: 4,
    image: images.dubai,
    tags: ["excursion", "walk"],
    included: ["Flight", "Hotel", "Breakfast"],
    leadContactTarget: "Dubai desk"
  },
  {
    id: "sharm-naama",
    title: "Naama Bay Easy Sea",
    destinationId: "sharm",
    country: "Egypt",
    city: "Sharm El Sheikh",
    hotelName: "Naama Blue Reef 5*",
    description: "Classic Red Sea holiday with warm water, beach routine and evening promenade.",
    price: 166000,
    currency: "RUB",
    startDate: "2026-06-20",
    endDate: "2026-06-27",
    duration: 7,
    image: images.sharm,
    tags: ["beach", "walk"],
    included: ["Flight", "Hotel", "All inclusive", "Transfer"],
    leadContactTarget: "Egypt desk"
  },
  {
    id: "sharm-reef",
    title: "Reef Snorkel Week",
    destinationId: "sharm",
    country: "Egypt",
    city: "Sharm El Sheikh",
    hotelName: "Ras Reef Resort 4*",
    description: "Snorkeling-focused beach week with house reef and quiet evenings.",
    price: 148000,
    currency: "RUB",
    startDate: "2026-06-24",
    endDate: "2026-07-01",
    duration: 7,
    image: images.sharm,
    tags: ["beach", "excursion"],
    included: ["Flight", "Hotel", "All inclusive", "Transfer"],
    leadContactTarget: "Egypt desk"
  },
  {
    id: "sharm-family",
    title: "Aqua Family Sharm",
    destinationId: "sharm",
    country: "Egypt",
    city: "Sharm El Sheikh",
    hotelName: "Aqua Sands Resort 5*",
    description: "Family resort with water slides, kids club and simple beach access.",
    price: 198000,
    currency: "RUB",
    startDate: "2026-06-22",
    endDate: "2026-06-30",
    duration: 8,
    image: images.sharm,
    tags: ["family", "beach"],
    included: ["Flight", "Hotel", "All inclusive", "Transfer"],
    leadContactTarget: "Egypt desk"
  },
  {
    id: "sharm-sinai",
    title: "Sinai Sun & Trips",
    destinationId: "sharm",
    country: "Egypt",
    city: "Sharm El Sheikh",
    hotelName: "Sinai Coast Hotel 4*",
    description: "Beach base for boat trips and short desert excursions.",
    price: 137000,
    currency: "RUB",
    startDate: "2026-06-27",
    endDate: "2026-07-03",
    duration: 6,
    image: images.sharm,
    tags: ["excursion", "beach"],
    included: ["Flight", "Hotel", "Breakfast", "Transfer"],
    leadContactTarget: "Egypt desk"
  },
  {
    id: "phuket-karon",
    title: "Karon Tropical Week",
    destinationId: "phuket",
    country: "Thailand",
    city: "Phuket",
    hotelName: "Karon Palm Resort 4*",
    description: "Tropical beach trip near cafes and long sandy coastline.",
    price: 243000,
    currency: "RUB",
    startDate: "2026-06-20",
    endDate: "2026-06-30",
    duration: 10,
    image: images.phuket,
    tags: ["beach", "walk"],
    included: ["Flight", "Hotel", "Breakfast", "Transfer"],
    leadContactTarget: "Thailand desk"
  },
  {
    id: "phuket-kata-family",
    title: "Kata Family Palms",
    destinationId: "phuket",
    country: "Thailand",
    city: "Phuket",
    hotelName: "Kata Family Palms 4*",
    description: "Family-friendly hotel with pool, calm area and flexible meal plan.",
    price: 267000,
    currency: "RUB",
    startDate: "2026-06-24",
    endDate: "2026-07-04",
    duration: 10,
    image: images.phuket,
    tags: ["family", "beach"],
    included: ["Flight", "Hotel", "Breakfast", "Transfer"],
    leadContactTarget: "Thailand desk"
  },
  {
    id: "phuket-island-hop",
    title: "Phuket Island Hop",
    destinationId: "phuket",
    country: "Thailand",
    city: "Phuket",
    hotelName: "Patong Bay Base 3*",
    description: "Budget-friendly base for island trips, markets and active evenings.",
    price: 198000,
    currency: "RUB",
    startDate: "2026-06-21",
    endDate: "2026-06-29",
    duration: 8,
    image: images.phuket,
    tags: ["excursion", "walk"],
    included: ["Flight", "Hotel", "Breakfast"],
    leadContactTarget: "Thailand desk"
  },
  {
    id: "phuket-quiet",
    title: "Nai Harn Slow Stay",
    destinationId: "phuket",
    country: "Thailand",
    city: "Phuket",
    hotelName: "Nai Harn Garden 4*",
    description: "Quieter corner of Phuket for slow mornings, beach walks and local cafes.",
    price: 229000,
    currency: "RUB",
    startDate: "2026-06-26",
    endDate: "2026-07-05",
    duration: 9,
    image: images.phuket,
    tags: ["walk", "beach"],
    included: ["Flight", "Hotel", "Breakfast", "Transfer"],
    leadContactTarget: "Thailand desk"
  },
  {
    id: "bali-nusa-dua",
    title: "Nusa Dua Soft Beach",
    destinationId: "bali",
    country: "Indonesia",
    city: "Bali",
    hotelName: "Nusa Dua Lagoon 5*",
    description: "Polished beach resort with calm rhythm and reliable hotel facilities.",
    price: 289000,
    currency: "RUB",
    startDate: "2026-06-20",
    endDate: "2026-06-30",
    duration: 10,
    image: images.bali,
    tags: ["beach", "family"],
    included: ["Flight", "Hotel", "Breakfast", "Transfer"],
    leadContactTarget: "Bali desk"
  },
  {
    id: "bali-ubud",
    title: "Ubud Green Walks",
    destinationId: "bali",
    country: "Indonesia",
    city: "Bali",
    hotelName: "Ubud Rice View 4*",
    description: "Green inland stay for walks, cafes, temples and day trips.",
    price: 236000,
    currency: "RUB",
    startDate: "2026-06-23",
    endDate: "2026-07-01",
    duration: 8,
    image: images.bali,
    tags: ["walk", "excursion"],
    included: ["Flight", "Hotel", "Breakfast", "Transfer"],
    leadContactTarget: "Bali desk"
  },
  {
    id: "bali-canggu",
    title: "Canggu Surf Mood",
    destinationId: "bali",
    country: "Indonesia",
    city: "Bali",
    hotelName: "Canggu Tide Hotel 4*",
    description: "Beach cafes, sunsets and relaxed island routine.",
    price: 251000,
    currency: "RUB",
    startDate: "2026-06-24",
    endDate: "2026-07-03",
    duration: 9,
    image: images.bali,
    tags: ["beach", "walk"],
    included: ["Flight", "Hotel", "Breakfast"],
    leadContactTarget: "Bali desk"
  },
  {
    id: "bali-family",
    title: "Sanur Family Breeze",
    destinationId: "bali",
    country: "Indonesia",
    city: "Bali",
    hotelName: "Sanur Breeze Resort 4*",
    description: "Softer beach area with calmer pace and family-friendly hotels.",
    price: 274000,
    currency: "RUB",
    startDate: "2026-06-27",
    endDate: "2026-07-07",
    duration: 10,
    image: images.bali,
    tags: ["family", "beach"],
    included: ["Flight", "Hotel", "Breakfast", "Transfer"],
    leadContactTarget: "Bali desk"
  },
  {
    id: "sochi-imereti",
    title: "Imereti Sea Week",
    destinationId: "sochi",
    country: "Russia",
    city: "Sochi",
    hotelName: "Imereti Coast 4*",
    description: "Black Sea stay with promenade, beaches and easy airport transfer.",
    price: 98000,
    currency: "RUB",
    startDate: "2026-06-20",
    endDate: "2026-06-27",
    duration: 7,
    image: images.sochi,
    tags: ["beach", "walk"],
    included: ["Flight", "Hotel", "Breakfast"],
    leadContactTarget: "Russia desk"
  },
  {
    id: "sochi-family",
    title: "Sochi Family Coast",
    destinationId: "sochi",
    country: "Russia",
    city: "Sochi",
    hotelName: "Sea Garden Family 4*",
    description: "Family trip with pool, beach access and short transfers.",
    price: 126000,
    currency: "RUB",
    startDate: "2026-06-23",
    endDate: "2026-06-30",
    duration: 7,
    image: images.sochi,
    tags: ["family", "beach"],
    included: ["Flight", "Hotel", "Breakfast", "Transfer"],
    leadContactTarget: "Russia desk"
  },
  {
    id: "sochi-rosa",
    title: "Rosa Khutor Air",
    destinationId: "sochi",
    country: "Russia",
    city: "Sochi",
    hotelName: "Rosa Valley Hotel 4*",
    description: "Mountain air, walks, cable cars and cooler evenings near the sea region.",
    price: 112000,
    currency: "RUB",
    startDate: "2026-06-21",
    endDate: "2026-06-27",
    duration: 6,
    image: images.sochi,
    tags: ["walk", "excursion"],
    included: ["Flight", "Hotel", "Breakfast"],
    leadContactTarget: "Russia desk"
  },
  {
    id: "sochi-short",
    title: "Sochi Long Weekend",
    destinationId: "sochi",
    country: "Russia",
    city: "Sochi",
    hotelName: "Central Promenade 3*",
    description: "Short city-and-sea break for walks, cafes and quick beach stops.",
    price: 72000,
    currency: "RUB",
    startDate: "2026-06-26",
    endDate: "2026-06-30",
    duration: 4,
    image: images.sochi,
    tags: ["walk", "beach"],
    included: ["Flight", "Hotel", "Breakfast"],
    leadContactTarget: "Russia desk"
  }
];

export const tourById = new Map(mockTours.map((tour) => [tour.id, tour]));
